### PR TITLE
Expose postgres/mysql URL parsing logic

### PR DESCRIPTION
**Pull request by tomhoule**

### CODE REVIEW

**Comment by pimeys** [comment]
Why not add methods to the rest of the connection parameters? The supported/unsupported is not necessary due to us not really sending the connection string to the crate. I'd like to see nice accessors for SSL, connection_limit etc.

**Comment by tomhoule** [comment]
Good point - I added only those I needed, but better be exhaustive. I'll add these.

**Comment by tomhoule** [comment]
@pimeys  done

**Comment by tomhoule** [comment]
The new methods return structs to preserve the exhaustiveness check we had before (i.e. the logging of unknown parameters).

**Pull request merged**
